### ISSUE TITLE
Release a new version with latest changes

### ISSUE THREAD

**Issue by yusdacra** [hamza1311/reqwasm#15]
It seems the version on crates.io does not contain features like `.binary()` on `Response` or the `WebSocket` fixes (#13)? I would like if a new version with these changes were published on crates.io :slightly_smiling_face:

**Comment by hamza1311** [comment]
I'm planning on it. I was hoping to get #11 done before publishing. I'll publish as soon as possible (and add example later)

**Comment by hamza1311** [comment]
0.3.0 is now released
