### ISSUE TITLE
Revert update to Edition 2021 back to Edition 2018

### ISSUE THREAD

**Issue by lukechu10** [hamza1311/reqwasm#17]
Updating to edition 2021 forces all dependents (reverse dependencies) on `reqwasm` to update their MSRV to 1.56 which is still very new and not necessarily broadly used. Since there doesn't seem to be any technical reason as to why `reqwasm` needs to be edition 2021, I strongly encourage you to change the edition back to 2018.

**Comment by hamza1311** [comment]
I see. I understand the problem. Would you like to making a PR reverting back to 2018 edition
