### ISSUE TITLE
Opening websocket to unavailable server panics

### ISSUE THREAD

**Issue by Barre** [hamza1311/reqwasm#20]
When trying to open a websocket to a server that is down such as:

```rust
let ws = match WebSocket::open("ws://127.0.0.1/path");

match ws {
    Ok(ws) => {
        log::info!("Ok")
    },
    Err(_) => {
        log::error!("Error");
    }
}
```

`ws` will never gets an `Error` and the app panics.

![image](https://user-images.githubusercontent.com/45085843/147322704-cb8670a1-7dd7-4f74-82b8-b4ebd05b0086.png)

**Comment by hamza1311** [comment]
Hi, this issue has been fixed in master. Life got in the way so I couldn't publish the release. I will do so soon.

**Comment by hamza1311** [comment]
A new version has been released with the fix.

**Comment by Barre** [comment]
Thank you @hamza1311 that's very kind!
