### ISSUE TITLE
How to handle websocket disconneciton

### ISSUE THREAD

**Issue by fbucek** [hamza1311/reqwasm#3]
Is it possible to handle WebSocket disconnection?

In example it is using unbounded channel, but the receiver never stop receving  `receiver.next().await` So I do not know how to notify, that it is no longer connected due to server or other error.

Or did I miss something?

```rust
spawn_local(async move {
    while let Some(m) = receiver.next().await {
        match m {
            Ok(Message::Text(m)) => console_log!("message", m),
            Ok(Message::Bytes(m)) => console_log!("message", format!("{:?}", m)),
            Err(e) => {}
        }
    }
    // unreachable
});
```

**Comment by hamza1311** [comment]
Does dropping the `WebSocket` instance not close the connection?

**Comment by fbucek** [comment]
I do know not If I understand correctly, but problem is not when I want to disconnect, but when connection is lost or server is stoped.  

When I stop websocket server, then I can see that e.g. firefox ( in inspect panel ) that connection is closed.

But on client side `while let Some(m) = receiver.next().await` loop never finishes and is ready to receive next message which will never come since connection is lost because server is stopped.

I want to know that connection is lost so I can try to reconnect in e.g. 60s or show button to reconnect.

**Comment by hamza1311** [comment]
I see, I misunderstood. This functionality is missing right now. Would you like to PR an implementation?  
In order to implement this, we'd need to listen to `onclose` event on the websocket and then close the channel when websocket is closed.

PS: sorry, it took me a while to get back to you
